### ISSUE TITLE
Replace 404 link on Examples -> Blogs 

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#3019]
## I'm submitting a...

```
[ ] Bug report
[ x ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Need to replace a 404 link on the "Blogs" page in the docs.

The author of the blog post "Cypress com Cucumber nos testes E2E" has requested that we replace the link to their blog post with an updated link since the URL has changed, and the [current link](https://medium.com/concretebr/2019/01/24/cypress-com-cucumber-nos-testes-e2e/) 404s. 

<img width="1186" alt="Screen Shot 2020-07-23 at 1 34 21 PM" src="https://user-images.githubusercontent.com/41870345/88324941-0b2af680-ccea-11ea-85a1-fb2a322d4dad.png">

[Here is the updated link](https://medium.com/assertqualityassurance/setting-cypress-and-cucumber-in-e2e-tests-6239adac1077).

**Comment by 7daytheory** [comment]
I'll do this one

**Comment by 7daytheory** [comment]
> I'll do this one

I found the next blog post had the same invalid link also

**Comment by magnolia-triplett** [comment]
@7daytheory thanks! I found the correct link for the next blog post too [here](https://imasters.com.br/front-end/testes-e2e-com-cypress-no-quasar-framework)

**Comment by 7daytheory** [comment]
> @7daytheory thanks! I found the correct link for the next blog post [here](https://imasters.com.br/front-end/testes-e2e-com-cypress-no-quasar-framework)

No problem! Added.

**Comment by jennifer-shehane** [comment]
Fixed in https://github.com/cypress-io/cypress-documentation/pull/3020

**Comment by uLucasFraga** [comment]
> Fixed in #3020

Hey, @jennifer-shehane and @7daytheory, the **fix** hasn't been reflected here yet, is there anything else to be done?
Thanks!

**Comment by jennifer-shehane** [comment]
@uLucasFraga Good question. It looks as if our auto-deployment of the docs has not been successful since yesterday. Will have to look into what's failing here. https://github.com/cypress-io/cypress-documentation/pull/3026

**Comment by jennifer-shehane** [comment]
K, it deployed this time properly. 

<img width="437" alt="Screen Shot 2020-07-29 at 12 42 40 PM" src="https://user-images.githubusercontent.com/1271364/88763371-0c03d280-d199-11ea-99ca-2e635fc60913.png">

**Comment by uLucasFraga** [comment]
Hey again, @jennifer-shehane!

It seems that the previous problem is still happening.
I’m not being redirected to the correct link:

 https://medium.com/assertqualityassurance/setting-cypress-and-cucumber-in-e2e-tests-6239adac1077

Thanks!
